x-svc: &service
  env_file:
    - "run/env/service.env"
  volumes:
    - conf:/wmsa/conf:ro
    - model:/wmsa/model
    - data:/wmsa/data
    - logs:/var/log/wmsa
    - dist:/dist
  networks:
    - wmsa
  depends_on:
    - mariadb

x-p1: &partition-1
  env_file:
    - "run/env/service.env"
  volumes:
    - conf:/wmsa/conf:ro
    - model:/wmsa/model
    - data:/wmsa/data
    - logs:/var/log/wmsa
    - dist:/dist
    - index-1:/idx
    - work-1:/work
    - backup-1:/backup
    - samples-1:/storage
  networks:
    - wmsa
  depends_on:
    - mariadb
  environment:
    - "WMSA_SERVICE_NODE=1"
x-p2: &partition-2
  env_file:
    - "run/env/service.env"
  volumes:
    - conf:/wmsa/conf:ro
    - model:/wmsa/model
    - data:/wmsa/data
    - logs:/var/log/wmsa
    - dist:/dist
    - index-2:/idx
    - work-2:/work
    - backup-2:/backup
    - samples-2:/storage
  networks:
    - wmsa
  depends_on:
    - mariadb
  environment:
    - "WMSA_SERVICE_NODE=2"

services:
  index-service-1:
    <<: *partition-1
    image: "marginalia.nu/index-service"
    container_name: "index-service-1"
  executor-service-1:
    <<: *partition-1
    image: "marginalia.nu/executor-service"
    container_name: "executor-service-1"
  index-service-2:
    <<: *partition-2
    image: "marginalia.nu/index-service"
    container_name: "index-service-2"
  executor-service-2:
    <<: *partition-2
    image: "marginalia.nu/executor-service"
    container_name: "executor-service-2"
  search-service:
    <<: *service
    image: "marginalia.nu/search-service"
    container_name: "search-service"
  assistant-service:
    <<: *service
    image: "marginalia.nu/assistant-service"
    container_name: "assistant-service"
  api-service:
    <<: *service
    image: "marginalia.nu/api-service"
    container_name: "api-service"
  query-service:
    <<: *service
    image: "marginalia.nu/query-service"
    container_name: "query-service"
  dating-service:
    <<: *service
    image: "marginalia.nu/dating-service"
    container_name: "dating-service"
  explorer-service:
    <<: *service
    image: "marginalia.nu/explorer-service"
    container_name: "explorer-service"
  control-service:
    <<: *service
    image: "marginalia.nu/control-service"
    container_name: "control-service"

  mariadb:
    image: "mariadb:lts"
    container_name: "mariadb"
    env_file: "run/env/mariadb.env"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "127.0.0.1:3306:3306/tcp"
    volumes:
      - db:/var/lib/mysql
      - "./code/common/db/src/main/resources/sql/current/:/docker-entrypoint-initdb.d/"
    networks:
      - wmsa
  nginx-gw:
    image: "nginx"
    container_name: "nginx-gw"
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8081:81"
      - "127.0.0.1:8082:82"
    volumes:
      - "./run/nginx-site.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - wmsa
    depends_on:
      - search-service
networks:
  wmsa:
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/db
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/logs
  model:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/model
  conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/conf
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/data
  dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/dist
  samples-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-1/samples
  index-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-1/index
  work-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-1/work
  backup-1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-1/backup
  samples-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-2/samples
  index-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-2/index
  work-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-2/work
  backup-2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: run/node-2/backup