global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels:
          - '__meta_docker_network_ip'
        target_label: '__address__'
        replacement: '$1:7000'